import {
  AUDIT_NOTE_PATTERN,
  buildProcessNote,
  parseProcessNotes,
  splitProcessNotes,
  classifyProcessNote,
} from '../lib/processHistory';

describe('buildProcessNote', () => {
  it('prefixes the message with a bracketed ISO timestamp', () => {
    expect(buildProcessNote('Something happened.', '2026-08-25T12:00:00.000Z'))
      .toBe('[2026-08-25T12:00:00.000Z] Something happened.');
  });

  it('defaults to the current time in a format the parser accepts', () => {
    const note = buildProcessNote('Something happened.');
    expect(AUDIT_NOTE_PATTERN.test(note)).toBe(true);
  });

  it('collapses internal newlines so the note stays a single chunk', () => {
    // A \n\n inside the message would split it into two chunks; the second would
    // fail AUDIT_NOTE_PATTERN and disappear from the timeline entirely.
    const note = buildProcessNote('First line.\n\nSecond line.', '2026-08-25T12:00:00.000Z');
    expect(note).toBe('[2026-08-25T12:00:00.000Z] First line. Second line.');
    expect(parseProcessNotes(note)).toHaveLength(1);
  });

  it('trims surrounding whitespace', () => {
    expect(buildProcessNote('  padded.  ', '2026-08-25T12:00:00.000Z'))
      .toBe('[2026-08-25T12:00:00.000Z] padded.');
  });
});

describe('parseProcessNotes', () => {
  it('returns an empty array for null, undefined, and empty input', () => {
    expect(parseProcessNotes(null)).toEqual([]);
    expect(parseProcessNotes(undefined)).toEqual([]);
    expect(parseProcessNotes('')).toEqual([]);
  });

  it('returns an empty array when notes contain only operator free text', () => {
    expect(parseProcessNotes('Called the lender, waiting on a callback.')).toEqual([]);
  });

  it('extracts timestamp and message from each audit chunk', () => {
    const notes = [
      '[2026-08-25T12:00:00.000Z] Resale Certificate completed by Jane Doe.',
      '[2026-08-25T13:00:00.000Z] Email sent to a@b.com by Jane Doe.',
    ].join('\n\n');

    expect(parseProcessNotes(notes)).toEqual([
      { timestamp: '2026-08-25T12:00:00.000Z', message: 'Resale Certificate completed by Jane Doe.' },
      { timestamp: '2026-08-25T13:00:00.000Z', message: 'Email sent to a@b.com by Jane Doe.' },
    ]);
  });

  it('ignores free text interleaved between audit entries', () => {
    const notes = [
      'Operator wrote this first.',
      '[2026-08-25T12:00:00.000Z] PDF generated by Jane Doe.',
      'And a follow-up comment.',
    ].join('\n\n');

    expect(parseProcessNotes(notes)).toEqual([
      { timestamp: '2026-08-25T12:00:00.000Z', message: 'PDF generated by Jane Doe.' },
    ]);
  });

  it('preserves stored order rather than sorting', () => {
    const notes = [
      '[2026-08-25T13:00:00.000Z] Later.',
      '[2026-08-25T12:00:00.000Z] Earlier.',
    ].join('\n\n');

    expect(parseProcessNotes(notes).map(e => e.message)).toEqual(['Later.', 'Earlier.']);
  });
});

describe('splitProcessNotes', () => {
  it('separates audit chunks from operator free text', () => {
    const notes = [
      '[2026-08-25T12:00:00.000Z] PDF generated by Jane Doe.',
      'Operator note here.',
    ].join('\n\n');

    expect(splitProcessNotes(notes)).toEqual({
      auditChunks: ['[2026-08-25T12:00:00.000Z] PDF generated by Jane Doe.'],
      freeText: 'Operator note here.',
    });
  });

  it('round-trips audit chunks unchanged when free text is edited', () => {
    // This is what the Comments & Notes editor does before POSTing to
    // /api/save-comments, which overwrites the whole notes column.
    const original = [
      '[2026-08-25T12:00:00.000Z] PDF generated by Jane Doe.',
      '[2026-08-25T13:00:00.000Z] Email sent to a@b.com by Jane Doe.',
      'Old comment.',
    ].join('\n\n');

    const { auditChunks } = splitProcessNotes(original);
    const rebuilt = `${auditChunks.join('\n\n')}\n\nNew comment.`;

    expect(parseProcessNotes(rebuilt)).toHaveLength(2);
    expect(splitProcessNotes(rebuilt).freeText).toBe('New comment.');
  });

  it('handles notes with no audit entries', () => {
    expect(splitProcessNotes('Just a comment.')).toEqual({
      auditChunks: [],
      freeText: 'Just a comment.',
    });
  });
});

describe('classifyProcessNote', () => {
  // Regression guard: every string below is produced by an API route that
  // already exists, and the expectation is CURRENT behaviour, not desired
  // behaviour. Adding the lender questionnaire rules must not change how any of
  // them classify, or historical timelines would re-render differently.
  const existingNotes = [
    ['Property corrected by Jane Doe: changed from A → B.',                 'correction'],
    ['Rush upgrade invoice ($50) created and emailed to a@b.com by Jane.',  'rush_invoice'],
    ['Package upgraded to rush by Jane Doe. Rush fee ($50) waived.',        'rush_upgrade'],
    ['Application rejected by Jane Doe. Reason: "bad data"',                'rejected'],
    ['Application cancelled by Jane Doe. Reason: "duplicate"',              'rejected'],
    ['Invoice paid by a@b.com ($50.00) for correction.',                    'paid'],
    ['Application details updated by Jane Doe.',                            'details'],
    ['Email sent for Maple HOA to a@b.com by Jane Doe.',                    'email'],
    ['PDF generated by Jane Doe.',                                          'default'],
  ];

  it.each(existingNotes)('classifies existing note %#: "%s" as %s', (message, expected) => {
    expect(classifyProcessNote(message)).toBe(expected);
  });

  // Pre-existing rules that match strings no route actually writes. These notes
  // render with the grey fallback clock today. Pinned so the gap is visible and
  // so a future wording fix has to update this block deliberately.
  const unmatchedByExistingRules = [
    // complete-task.js writes "<Label> completed by <admin>.", but the rule
    // tests for 'task completed' / 'was completed'.
    'Property Inspection Form completed by Jane Doe.',
    'Resale Certificate for Maple HOA completed by Jane Doe.',
    'Settlement Form completed by Jane Doe.',
    // requester-resend-email.js writes "resent", the rule tests for 'resend'.
    'Email resent by Jane Doe.',
    // send-public-offering-email.js / send-info-packet-email.js write "sent to",
    // which is not one of the email rule's substrings.
    'Public Offering Statement sent to a@b.com.',
    'Info Packet documents sent to a@b.com.',
    // Nothing writes an assignment note, so the 'assigned' rule is unreachable.
  ];

  it.each(unmatchedByExistingRules)('falls back to default for unmatched existing note: "%s"', (message) => {
    expect(classifyProcessNote(message)).toBe('default');
  });

  const lqNotes = [
    ['Original LQ file uploaded by admin on behalf of requester (emailed document).', 'lq_original'],
    ['Original lender questionnaire downloaded by Jane Doe.',                         'lq_download'],
    ['Completed lender questionnaire uploaded by Jane Doe.',                          'lq_upload'],
    ['Lender questionnaire edited in the PDF editor by Jane Doe.',                    'lq_edit'],
    ['Lender questionnaire emailed to a@b.com by Jane Doe.',                          'email'],
  ];

  it.each(lqNotes)('classifies lender questionnaire note "%s" as %s', (message, expected) => {
    expect(classifyProcessNote(message)).toBe(expected);
  });

  it('does not let the historical LQ note fall into the email rule', () => {
    // It contains "emailed document", which must not match "emailed to".
    expect(classifyProcessNote('Original LQ file uploaded by admin on behalf of requester (emailed document).'))
      .toBe('lq_original');
  });

  it('does not let the completed-upload note fall into the task rule', () => {
    // Rule order puts 'was completed' ahead of the LQ rules, so wording that
    // reads "...was completed and uploaded" would silently become a generic task.
    expect(classifyProcessNote('Completed lender questionnaire uploaded by Jane Doe.')).toBe('lq_upload');
    expect(classifyProcessNote('Lender questionnaire was completed and uploaded by Jane Doe.')).toBe('task');
  });

  it('routes the LQ email note to the shared email type, matching resale', () => {
    expect(classifyProcessNote('Lender questionnaire emailed to a@b.com by Jane Doe.'))
      .toBe(classifyProcessNote('Email sent for Maple HOA to a@b.com by Jane Doe.'));
  });

  it('is case insensitive', () => {
    expect(classifyProcessNote('ORIGINAL LENDER QUESTIONNAIRE DOWNLOADED BY JANE.')).toBe('lq_download');
  });

  it('falls back to default for unrecognised messages and empty input', () => {
    expect(classifyProcessNote('Something entirely new happened.')).toBe('default');
    expect(classifyProcessNote('')).toBe('default');
    expect(classifyProcessNote(null)).toBe('default');
  });
});
